# Generated by Django 4.2.3 on 2024-02-20 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(default='', max_length=70)),
                ('mobileno', models.CharField(default='', max_length=70, unique=True)),
                ('email', models.CharField(default='', max_length=70, unique=True)),
                ('password', models.CharField(default='', max_length=70)),
                ('picture', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannername', models.CharField(default='', max_length=70)),
                ('bannericon', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(default='', max_length=70)),
                ('brandicon', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maincategoryname', models.CharField(default='', max_length=70)),
                ('icon', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=100)),
                ('producticon', models.ImageField(upload_to='static/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.brand')),
                ('mainCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(default='', max_length=70)),
                ('subcategoryicon', models.ImageField(upload_to='static/')),
                ('mainCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproductname', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=100)),
                ('quntity', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('offerprice', models.BigIntegerField()),
                ('offertype', models.CharField(default='', max_length=50)),
                ('picture', models.TextField(default='')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.brand')),
                ('mainCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.maincategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.product')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.subcategory'),
        ),
    ]
