# Generated by Django 4.2.3 on 2024-04-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='color',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='size',
            field=models.CharField(default='', max_length=70),
        ),
    ]
