# Generated by Django 4.2.3 on 2024-04-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0002_productdetail_color_productdetail_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='color',
            new_name='colour',
        ),
    ]
